# docker-compose.yml

services:
  # service named 'db'
  db:
    restart: always
    image: mongo:latest
    command: ["--wiredTigerCacheSizeGB", "0.25"]
    ports: 
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
